### ISSUE TITLE
ISO8601 timezone datetime

### ISSUE THREAD

**Issue by tomasd** [schematics/schematics#173]
According to http://en.wikipedia.org/wiki/ISO_8601 datetime could be of 3 types:
- local datetime
- utc datetime
- timezone offset datetime

Currently only the 1st option is available in schematics. Would it be possible to support  the other ones? 

For instance this call parses timezone correclty from ISO8601:
import dateutil.parser
yourdate = dateutil.parser.parse(datestring)

**Comment by bintoro** [comment]
How about modifying `DateTimeType` so that it would accept a pluggable parser object? That way developers could use an external library of their choosing, be it dateutil, Arrow, or whatever.

**Comment by bintoro** [comment]
Fixed via #358.
