### ISSUE TITLE
no attribute '_unbound_fields'

### ISSUE THREAD

**Issue by ryanolson** [schematics/schematics#175]
I am getting the following error:
AttributeError: type object 'User' has no attribute '_unbound_fields'

This seems to have something to do with the ModelMeta __iter__ function:
https://github.com/j2labs/schematics/blob/c1b3d6c753608a441188c00c534397d2dd0030cf/schematics/models.py

pip list | grep schematics
couchdb-schematics (0.1.0-beta)
schematics (0.9-2)

This is from a release 0.9-2.  I don't think that code was intended to go out ...

**Comment by bintoro** [comment]
Looks like a historical bug that doesn't exist anymore.
