### ISSUE TITLE
Specified version on docs must be updated too

### ISSUE THREAD

**Issue by puentesarrin** [schematics/schematics#179]
Schematics 0.9.3 was released, it would great to update the specified version on the following lines in Sphinx configuration:

https://github.com/j2labs/schematics/blob/master/docs/conf.py#L54-L56

**Comment by bintoro** [comment]
This was fixed in 58c26ca0c788e72f441494c9825f3ac35bc85030. The Sphinx config now gets the version number from `schematics/__init__.py`.
