### ISSUE TITLE
_force_list issue

### ISSUE THREAD

**Issue by caelx** [schematics/schematics#183]
I'm having an issue with schematics when I try to load a list which is actually a dictionary.  The code tries to convert it to a list (which is the behavior I want) but the conversion fails and it doesn't return the expected value.

Unfortunately I have to do it this way because sometimes it's a list and sometimes it's not a list.

Here's a code example to generate the issue I am seeing:

```
#!/usr/bin/python

import json
import logging
from schematics.models import Model
from schematics.types import StringType
from schematics.types.base import BaseType
from schematics.types.compound import ListType, ModelType

class ForceListType(ListType):
    def _force_list(self, value):
        try:
            ListType._force_list(self, value)
        except ValueError:
            return [value]

class Horses(Model):
    class PonyDetected(Model):
        class Pony(Model):
            timestamp_at = StringType(required=True, serialized_name='timestamp-at')
            ponysum = StringType()
            type = StringType()
            name = StringType()
        pony = ListType(ModelType(Pony))
    pony_detected = ModelType(PonyDetected, serialized_name='pony-detected')

if __name__ == '__main__':
    json1 = {
    "pony-detected": {
        "pony": {
            "timestamp-at": "right now",
            "ponysum": "100",
            "type": "gray",
            "name": "mr pony"
            }
        }
    }
    horses = Horses(json1)
    print horses.pony_detected.pony[-1].name
```

![2013-11-06 18_45_43-administrator_ c__windows_system32_cmd exe](https://f.cloud.github.com/assets/1686351/1489171/7d608464-4767-11e3-83b5-b43b798f6039.png)

If you change ListType to ForceListType you can get the expected parsing result.  The reason is that the code tries to do the dictionary conversion and fails, it has no provision to catch the value error and thus needs to be changed.

**Comment by bintoro** [comment]
The issue here is basically about the structure of the source data varying unpredictably. This kind of thing is best solved via an upcoming feature (#269) providing a way to sanitize the input before it hits the import machinery.
