### ISSUE TITLE
subclassed models are not serialized

### ISSUE THREAD

**Issue by poundifdef** [schematics/schematics#184]
Consider the following:

```
from schematics.models import Model
from schematics.types import StringType
from schematics.types.compound import ModelType

class Asset(Model):
    file_name = StringType()

class S3Asset(Asset):
    bucket_name = StringType()

class Product(Model):
    title = StringType()
    asset = ModelType(Asset)
    
asset = S3Asset({'bucket_name': 'assets_bucket', 'file_name': 'bar'})

product = Product({'title': 'baz', 'asset': asset})
print product.to_native()
```

This code outputs: `{'asset': {'storage_location': u's3'}, 'title': u'baz'}`

Because "Product.asset" is defined as an "Asset", rather than an S3Asset, schematics does not serialize the S3Asset-specific fields.

I believe this is because the list of fields to be serialized is defined in ModelMeta, before the model "knows" that it is being passed a subclass.

I'm not yet sure of how I'd fix this - perhaps update `to_primitive` to do self inspection there, rather than ModelMeta and using `self.__class__`?

**Comment by bintoro** [comment]
Closing, as `PolyModelType` has been around for a while now. If there are any remaining concerns, please open a new issue.

**Comment by poundifdef** [comment]
Very cool. Thank you for tracking and acting on this!
