### ISSUE TITLE
78% test coverage

### ISSUE THREAD

**Issue by j2labs** [schematics/schematics#203]
I know we can do better.  Let's get there.

    =============================== 147 passed in 0.69 seconds ===============================
    Name                            Stmts   Miss  Cover
    ---------------------------------------------------
    schematics/__init__                 2      0   100%
    schematics/contrib/__init__         0      0   100%
    schematics/contrib/mongo           20     20     0%
    schematics/datastructures          93     40    57%
    schematics/exceptions              30      1    97%
    schematics/models                 171     27    84%
    schematics/transforms             205     16    92%
    schematics/types/__init__           1      0   100%
    schematics/types/base             352     93    74%
    schematics/types/compound         177     24    86%
    schematics/types/serializable      22      1    95%
    schematics/types/temporal          26     26     0%
    schematics/validate                46      1    98%
    ---------------------------------------------------
    TOTAL                            1145    249    78%

**Comment by bintoro** [comment]
Historical meta issue.
