### ISSUE TITLE
Whatever returned from model validation methods gets disregarded

### ISSUE THREAD

**Issue by Gennady-Andreyev** [schematics/schematics#206]
According to docs / examples, model-level validation methods return ["clean" values](http://schematics.readthedocs.org/en/latest/usage/validation.html#model-level-validation). But current implementation of _validate_model() [doesn't expect any return value](https://github.com/j2labs/schematics/blob/master/schematics/validate.py#L82), so whatever returned from model validation methods gets disregarded.

**Comment by chase-seibert** [comment]
Specifically, the validators should have the opportunity to return an altered value.

**Comment by edc** [comment]
> According to docs / examples, model-level validation methods return "clean" values. 

The docs do not explicitly say that, and the examples are not consistent about it.

>  it could be that most people have been following the docs and returning something from their validator methods, but it's hard to tell.

I think most users are *not* returning clean values from validators. So I am in favor of explicitly decorate the validator functions if they want to modify value. For validator *method* on the model class, they can already alter value by mutating the `data` argument, but returning the clean value is indeed a better approach.

On a related note: we need to correct the document to emphasize the validator methods work as class methods (i.e. it's clearer to name the first argument `cls`).

**Comment by bintoro** [comment]
As @lkraider pointed out in #355, manipulating a field's value in the midst of a validation run can be somewhat precarious. Also, I believe that cleaning up a field's value is mostly associated with the import stage. In contrast, validation may be performed multiple times during the lifetime of a model instance.

For these reasons, I'm now thinking validators should only be able to accept or reject the value.

Having the ability to automatically sanitize or normalize a field makes sense to me, but I think it should be an independent step, not a part of the validation routine.

If a value must be adjusted in response to some validation error, it's better that the validator communicates this information in the error object, and the modification is done outside the loop. Error objects are in need of an overhaul anyway, and it would seem like a good idea to make room for error codes and similar metadata.

**Comment by lkraider** [comment]
This needs a compelling rationale that is not already served by simply implementing your own types. 

With the serializable setters now merged in, you can create virtual types that have access to the instance if required.

**Comment by bintoro** [comment]
This issue has been acting as a reminder to consider implementing a value-sanitization step to complement the import step. How is that sort of thing made redundant by settable serializables?

**Comment by lkraider** [comment]
@bintoro Before the setters all value-sanitization was done by the types in the convert step, and value-filtering in the validation step.

The setters now allow to access instance state in the convert step and also mutate instance data, which adds this flexibility.
