### ISSUE TITLE
How can I validate partial data ? Need to update 

### ISSUE THREAD

**Issue by dridk** [schematics/schematics#237]
My model is : 

```
public User(model):
    email = EmailType()
    pass = StringType()
```

When I get an update request in json { "pass": "newpassword"}  , I pass it to my User(), validate() and get my validate json. Unfortunally, I get a new "email" field set to None. 
How can I avoid that ?

**Comment by rskumar** [comment]
Can I define what fields to skip for `required` validation? If I have 3 fields A, B, C, I want to skip just A but I want to be get B and C validated? 

If I do `partial=True`, then even if B and C are required and not in data, it will pass.

**Comment by lkraider** [comment]
You can check the exception for the field you want to skip and then ignore it.

**Comment by rskumar** [comment]
Yup that will work for me :) .
But I think this cannot be a good solution, and devs will face such scenario many times working on REST apis where they define a schema and use it (DRY) for partial checks (like in http patch update).

**Comment by lkraider** [comment]
How would you like it to work?

**Comment by rskumar** [comment]
Just a thought, 
```
class A(Model):
    ...
class B(A):
    ignore_fields=('x', 'y',)

# or
b = B(..., ignore_fields=['x', 'y'])
b.validate()   # auto partial
```
Many ways, all to improve DRY.
