### ISSUE TITLE
"Rogue field" when monkeypatching model

### ISSUE THREAD

**Issue by cristobalcl** [schematics/schematics#238]
Hello,

I'm trying to "monkey-patch" a class that is a Schematics model in order to add fields and change/add functionality globally.

I'm using this pattern (from Guido, https://mail.python.org/pipermail/python-dev/2008-January/076194.html):

```python
def monkeypatch_class(name, bases, namespace):
    assert len(bases) == 1, "Exactly one base class required"
    base = bases[0]
    for name, value in namespace.iteritems():
        if name != "__metaclass__":
            setattr(base, name, value)
    return base

import <somewhere>

class <newclass>(<somewhere>.<someclass>):
    __metaclass__ = monkeypatch_class
    newField = IntType()

    def __init__(...): ...
    def <method1>(...): ...
    def <method2>(...): ...
    ...

<somewhere>.<someclass> = <newclass>
```

This seems to work, the new `__init__` is called, but I get the message when I call <newclass> super `__init__`:

```
schematics.exceptions.ModelConversionError: {'newField': 'Rogue field'}
```

It seems that the methods and field are added but the model is not updated. Any suggestion?

Thanks.

**Comment by kracekumar** [comment]
Please reopen if you disagree.
