### ISSUE TITLE
import_data with `None` value

### ISSUE THREAD

**Issue by st4lk** [schematics/schematics#249]
I'am expected such new test to pass:

```
# test_models.py

def test_model_import_data_nullify():
    class User(Model):
        name = StringType()
        age = IntType()
        votes = IntType(default=0)

    user = User(dict(name="Ivan", age=18))
    user.import_data(dict(age=None))
    assert user.age is None

    assert user.votes == 0
    user.import_data(dict(votes=5))
    assert user.votes == 5

    user.import_data(dict(votes=None))
    assert user.votes == 0

    user.import_data(dict(votes=0))
    assert user.votes == 0
```

So, if we explicitly provide `None` as value for some model field, then set to default value or to `None`. 
But, with current code, `None` values are just ignored and the value remains the same after `import_data`.

To make this test pass, all is needed is to modify code in [`import_data`](https://github.com/schematics/schematics/blob/bff12fc8cdb7f86ad977035eb033f5f4ca01da2d/schematics/models.py#L237) method:

    def import_data(self, raw_data, **kw):
        """
        Converts and imports the raw data into the instance of the model
        according to the fields in the model.

        :param raw_data:
            The data to be imported.
        """
        data = self.convert(raw_data, **kw)
        for k in data.keys():
           if data[k] is None and k not in raw_data:
               del data[k]
        self._data.update(data)
        return self

All other tests will still pass. I can make a pull request, if it not break some architecture decisions.

**Comment by bintoro** [comment]
The PR resolving this (#372) was merged into development last week and will be included in the upcoming v2.0 release.
