### ISSUE TITLE
Documentation is not automatically updating

### ISSUE THREAD

**Issue by charlax** [schematics/schematics#277]
It seems that the documentation hasn't updated in a while, according to https://readthedocs.org/projects/schematics/

Despite my merged PR from yesterday, the documentation hasn't changed:

* Github links are still outdated: http://schematics.readthedocs.org/en/latest/install.html#install-from-github
* The autodocumentation is broken: http://schematics.readthedocs.org/en/latest/api/models.html

**Comment by breerly** [comment]
+1 - lets do this

**Comment by charlax** [comment]
Any update here?

**Comment by j2labs** [comment]
Krace, let me know if you need anything from me.

On Thursday, March 12, 2015, Charles-Axel Dein <notifications@github.com>
wrote:

> Any update here?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/schematics/schematics/issues/277#issuecomment-78614481>
> .
>


-- 
jms dnns
jmsdnns.com | @jmsdnns <https://twitter.com/jmsdnns>

**Comment by bintoro** [comment]
If this is considered desirable, then it's just a matter of switching on the appropriate hook on RTD. @jmsdnns would need to set this up.

But building the docs manually is just a click of a button, and that way you'll also see immediately if they fail to build. Perhaps RTD can be configured to send out an alert in case of a failed build, but if not, I think I actually prefer manual operation.

**Comment by bintoro** [comment]
Apparently RTD doesn't need a token, so I was able to set up the hook myself. However, it triggers the build on every single commit, so I'm going to turn it off for now. If the docs start seeing more frequent updates, we can reactivate the feature anytime.
