### ISSUE TITLE
Email validation rule for long TLDs

### ISSUE THREAD

**Issue by myroslav** [schematics/schematics#299]
Recently there was increase of TLD segment lenth from 6 to 10 characters, but there are longer domain names (https://github.com/schematics/schematics/commit/2f90a4ad399a0f4fe8a68d1ddd64ad00d63efb05#commitcomment-10467770), especially the ones that are international (see http://www.iana.org/domains/root/db).

We'd welcome the pypi release after this bug is fixed. Should we provide pull request?

**Comment by kracekumar** [comment]
Please send a pull request. We will release version in April first week or
second week to pypi.

On Mon, Mar 30, 2015 at 7:14 PM, Myroslav Opyr <notifications@github.com>
wrote:

> Recently there was increase of TLD segment lenth from 6 to 10 characters,
> but there are longer domain names (2f90a4a#commitcomment-10467770
> <https://github.com/schematics/schematics/commit/2f90a4ad399a0f4fe8a68d1ddd64ad00d63efb05#commitcomment-10467770>),
> especially the ones that are international (see
> http://www.iana.org/domains/root/db).
>
> We'd welcome the pypi release after this bug is fixed. Should we provide
> pull request?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/schematics/schematics/issues/299>.
>



-- 
Regards
Kracekumar Ramaraju
http://kracekumar.com
+91 85530 29521

**Comment by myroslav** [comment]
Should we close this since #300 is merged, or it can be opened until release is pushed to pypi?

**Comment by kracekumar** [comment]
Sorry, my bad. We will close this.
