### ISSUE TITLE
URLType regex doesn't match urls that have subdomains with underscores

### ISSUE THREAD

**Issue by jordonwii** [schematics/schematics#326]
If you use the URL_REGEX value from the URLType, it doesn't match the following valid url: `http://my_subdomain.mydomain.com/` If you remove the underscore, it works. 

It seems like the best thing here might be to use another project's url regex. Django, for example, has one that's well-tested and does work on the above url: https://github.com/django/django/blob/f8cc464452f495fce2a3d6f7494396c8f798a1e6/django/core/validators.py#L67

**Comment by jmsdnns** [comment]
I can agree with this. Would you willing to make a PR for it?

**Comment by bintoro** [comment]
@jordonwii Underscores are not valid in hostnames. Django's validator doesn't accept underscores either.

If the Django code is validating `"my_subdomain"` for you, you're probably running copypasted code under Python 2 without `unicode_literals` enabled. In that case the regex pattern gets built incorrectly and will match things it shouldn't match.

Try changing `"ul = '\u00a1-\uffff'"` to `ul = u'\u00a1-\uffff'"` (or use Python 3) and notice how the URL doesn't validate anymore.
