### ISSUE TITLE
Model that contains field of of its type (same ModelType as itself)

### ISSUE THREAD

**Issue by mjrk** [schematics/schematics#330]
See the following schema

    class Expression(Model):

        expressions = ListType(ModelType(Expression))

Unfortunately, this is not possible as during class definition `Expression` is unknown. I could not find how to do this in the docs, searching `schematics/models.py` doesn't seem this is implemented. However, maybe I missed something as it seems a common use case to me.

IMHO this could be implemented in the `ModelMeta` class after the `klass` creation (see models.py). Could it work to set the field value to `klass` in those cases? Either with a special type `SelfType` or some DSL.

Or we could add a more explicit way to add custom fields - e.g. a method which's return value is used to extend the `klass`' -fields after initialization.

Suggestions?

**Comment by lkraider** [comment]
I went with the second option and added an `append_field` method to the Model:
https://github.com/nKey/schematics/blob/0ea74550b695ac962aab1828f63f44b909dfcdd7/schematics/models.py#L130

**Comment by bintoro** [comment]
It would certainly be neat to be able to specify self-referential fields right there in the model definition.

Any opinions on what the syntax should look like?

```python
class Node(Model):
    
    children = ListType(ModelType()) # no argument
```

```python
class Node(Model):
    
    children = ListType(ModelType(SelfRef)) # some placeholder object
```

```python
class Node(Model):
    
    children = ListType(ModelType('Node')) # the name of the model
```

**Comment by mjrk** [comment]
Personally, I like 

```python
class Node

    children = ListType(ModelType('Node'))
```

because it's the most explicit and you find all references with one search. On the other hand, it might make people believe they can use strings also for other models. Still +1 for it.

Using a placeholder (which I'd like second most) IMHO `schematics.types.compound.Self` seems straight forward.

Thanks a lot for your answer and great work btw.!

**Comment by bintoro** [comment]
@mjrk The syntax using the name of the model was my preference as well.

An implementation is now up for review as PR #335.

**Comment by bintoro** [comment]
This now exists in `development` and will be part of the next release (likely v1.2.0).

**Comment by mjrk** [comment]
Oh, with the work on v2.0.0 - will there be a version v1.2.0? Would be awesome

**Comment by bintoro** [comment]
@mjrk I considered making an interim release, but the thing is, there's really no specific point in history where it would clearly make sense. The road from v1.1.1 to v2.0.0 involves a series of small backward-incompatible changes (mainly for users who have implemented their own types), and by far the best way to deal with them is all at once.

I've added a recommendation to the README for new users to just get the latest development release.

**Comment by mjrk** [comment]
Ah, ok. This was actually the point - to have this feature without the backward-incompatible changes. However, I went for the lkraider's solution for the moment.

Thanks for your reply!
