### ISSUE TITLE
[Docs] page error

### ISSUE THREAD

**Issue by chhantyal** [schematics/schematics#334]
Page is broken and gives me following error:

`
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.grokthedocs.com/api/v1/queuedvisits/. (Reason: CORS header 'Access-Control-Allow-Origin' missing).
`

**Comment by bintoro** [comment]
Thanks for noticing this. The two things are unrelated, though.

The error is about `api.grokthedocs.com` not responding with a CORS header. Not a Schematics issue.

The appearance of the docs was broken because of a change at Read the Docs. I just pushed a commit that fixes the theme config.
