### ISSUE TITLE
export_loop() vs. to_primitive()

### ISSUE THREAD

**Issue by bintoro** [schematics/schematics#337]
All the compound types define both `export_loop` and `to_primitive` methods, but `to_primitive` never seems to be called.

Am I right in assuming that, for compound types, `to_primitive` is just a historical remnant that's been superseded by `export_loop`? And that there are two differently named methods simply because the argument lists are different?

If yes, then obviously it would be ideal to unify the methods so that `field.to_primitive(...)` would accomplish the same thing for both simple and complex types. There's going to be an opportunity to do just that when #266/#316/#318 is implemented, since it involves a one-time method signature change across the board in order to future-proof against further such changes.

**Comment by jmsdnns** [comment]
I believe this is correct. The original idea was that you could always call `to_primitive` on a type and it would just work. But `export_loop` became the way we'd pass around a transformation function, instead of assuming anything about whether or not a primitive was desired.

From then on, the compound types were containers and thus pathways towards getting to types that actually had `to_primitive` or `to_native` on them.

Would love a PR removing those methods, assuming tests are still good.

**Comment by bintoro** [comment]
The redundant methods have been axed via #342. Not having them around helps avoid confusion, but I'll leave this issue open, as the ultimate solution is a single interface that works for both simple and compound types.

**Comment by jmsdnns** [comment]
I'm not sure I agree on the single interface. I think an export loop is only useful when you are unpacking something with multiple values in it, like a model or compound type.

But, I think what you're talking about gets us closer to thinking about how to remove `ModelType` and possibly just have `Model` instances behave more like types. It feels to me like Models should just behave like types. They already have a `to_primitive` and `to_native` implementation.

Maybe it's just that I haven't been active in this codebase in a few years, but the `ModelType` really seems useless to me today. [Look at this](https://github.com/schematics/schematics/blob/development/schematics/types/compound.py#L59), it doesn't do anything the model wouldn't already do.

Hmm.

**Comment by bintoro** [comment]
Passing around the transformation function will not be a problem. See #266.

What I want is to get rid of kludgy conditional paths like [this](https://github.com/schematics/schematics/blob/development/schematics/transforms.py#L173) and [this](https://github.com/schematics/schematics/blob/development/schematics/types/serializable.py#L49).

**Comment by jmsdnns** [comment]
Hmm. I guess if these details are tucked away behind `to_native` and
`to_primitive` (_which likely still call export_loop_), we can always call
field_converter and know it'll work.

On Tue, Oct 20, 2015 at 3:41 PM, Kalle Tuure <notifications@github.com>
wrote:

> Passing around the transformation function will not be a problem. See #266
> <https://github.com/schematics/schematics/pull/266>.
>
> What I want is to get rid of kludgy conditional paths like this
> <https://github.com/schematics/schematics/blob/development/schematics/transforms.py#L173>
> and this
> <https://github.com/schematics/schematics/blob/development/schematics/types/serializable.py#L49>
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/schematics/schematics/issues/337#issuecomment-149679872>
> .
>



-- 
jms dnns
me <http://jmsdnns.com> // facebook <https://www.facebook.com/jmsdnns> //
github <https://github.com/jmsdnns/> // twitter
<https://twitter.com/jmsdnns>

**Comment by bintoro** [comment]
[Xref #359]

The docstring of `export_loop` states:

```
:param field_converter:
    This function is applied to every field found in ``instance_or_dict``.
```

But in actuality there's this:

```python
if hasattr(field, 'export_loop'):
    shaped = field.export_loop(...)
else:
    shaped = field_converter(...)
```

Thus, putting a model through `export_loop` always produces a `dict`, regardless of what the supplied field converter was.

What this means is that there are two notions of "native" when it comes to models:

  * When importing, `to_native` generates model instances.
  * When exporting, `to_native` generates dictionaries.

The point, as I understand it, is that you can run `Model.to_native()` and send the result to, say, PyMongo, which understands various Python types but not models.

Now, imagine a custom type `FooType` that takes some input and converts it to an instance of `FooClass`. Running `Model.to_native()` would preserve the `FooClass` representation, rendering the result useless to PyMongo.

So, clearly it's not enough to special case models. Each type should be able to decide for itself whether the "interoperable" representation should be the native or the primitive form (or perhaps something else entirely).

To put it another way, two conversion methods are not enough. There should be three:

  * `to_native` to create the internal, rich representation (`datetime`, `Model`, `FooClass`)
  * `to_python` to create the interoperable representation (`datetime`, `dict`, `dict`)
  * `to_primitive` to create the language-independent representation (`str`, `dict`, `dict`)

Virtually all types could just map `to_python` to either `to_native` or `to_primitive` as appropriate.

`Model.to_python()` would be equivalent to the `Model.to_native()` of today, except that it would be able to correctly deal with all rich constructs, not just models.

***

`export_loop` was meant to be independent of the desired output format, just blindly applying the field converter. This plan would take that design to its conclusion. Of course there are many ways to accomplish the same, so I'd like to hear what others think.

**Comment by lkraider** [comment]
I don't see the need of `to_python` in your PyMongo example, why not export using `to_primitive`?

**Comment by bintoro** [comment]
> I don't see the need of to_python in your PyMongo example, why not export using `to_primitive`?

Right, this is what I was asking yesterday over at #359 — I didn't get why `Model.to_native()` existed in the first place.

The answer is that PyMongo takes native `datetime` objects, for instance, and you want to preserve those while converting models to dictionaries.

So effectively `Model.to_native()` today means: "export everything as native except models as primitive", and that's why we have `if hasattr(field, 'export_loop')` in `export_loop`. The purpose of the conditional is to act as a context-sensitive switch between `to_native` and `to_primitive` when the user calls `Model.to_native()`.

**Comment by jmsdnns** [comment]
>
> we should have something like
>
> field_converter = lambda field, value: field.export(value, profile)
>
> where profile would indicate the type of the output, whether it's
> primitive, native, or some custom format.
>
I might be able to agree, depending on what the profile looks like.

Could you share an example of what you have in mind?

**Comment by bintoro** [comment]
> I might be able to agree, depending on what the profile looks like. Could you share an example of what you have in mind?

I was thinking just a string/constant. I don't foresee a need for anything more sophisticated than that.

I've already written a patch. It's quite simple, actually, but it builds on #359, so I'll submit the PR once that one's merged.
