### ISSUE TITLE
DecimalType UnicodeEncodeError 

### ISSUE THREAD

**Issue by tdenisova** [schematics/schematics#354]
Got an `UnicodeEncodeError` on `DecimalType`  validation when using  unicode string that contains non-ascii characters.

It fails on string formatting for ConversionError:
```
File "/schematics/types/base.py", line 559, in to_native
    raise ConversionError(self.messages['number_coerce'].format(value))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-4: ordinal not in range(128)
```
Variable values:
self.messages['number_coerce'] ==  "Number '{0}' failed to convert to a decimal"
value == u'единица'

schematics==1.0.4
python 2.7

**Comment by bintoro** [comment]
This should now work on the development branch. The patch will also be a last-minute addition to Schematics v1.1.1 that will be released shortly.
