### ISSUE TITLE
How to apply fields' default values

### ISSUE THREAD

**Issue by bintoro** [schematics/schematics#360]
The current Schematics is very eager to insert default values at every turn:

```python
class Foo(Model):
    s = StringType(default='blah')
```
```python
>>> f = Foo()
>>> f._data
{'s': u'blah'}
```
```python
>>> f = Foo({'s': None})
>>> f._data
{'s': u'blah'}
```
```python
>>> f = Foo()
>>> f.s = None
>>> f.import_data({'s': None})._data
{'s': u'blah'}
```
```python
>>> f = Foo()
>>> f.s = None
>>> f.import_data({})._data
{'s': u'blah'}
```

There's no way to stop the default from being applied.

**Here's how I believe this should work in 2.0:**

* Defaults are only applied to missing entries. Explicit `None` values would remain `None`.

* When `partial` is `True`, defaults are *not* applied at all. It makes zero sense for defaults to pop up when you specifially indicate you're working with partial data.

* A switch named `apply_defaults` would be available to force defaults for partial data or, conversely, leave them out from whole objects.

Any objections?

There's nothing here that couldn't be implemented on top of the current Schematics, but at the latest this must be sorted out when the undefined feature appears, and the only thing it depends on now is #359.

**Comment by j2labs** [comment]
Agreed. Go for it!

On Wed, Nov 18, 2015 at 1:52 PM, Kalle Tuure <notifications@github.com>
wrote:

> The current Schematics is very eager to insert default values at every
> turn:
>
> class Foo(Model):
>     s = StringType(default='blah')
>
> >>> f = Foo()>>> f._data
> {'s': u'blah'}
>
> >>> f = Foo({'s': None})>>> f._data
> {'s': u'blah'}
>
> >>> f = Foo()>>> f.s = None>>> f.import_data({'s': None})._data
> {'s': u'blah'}
>
> >>> f = Foo()>>> f.s = None>>> f.import_data({})._data
> {'s': u'blah'}
>
> There's no way to prevent the default value from being set.
>
> *Here's how I believe this should work in 2.0:*
>
>    -
>
>    Defaults are only applied to missing entries. Explicit None values
>    would remain None.
>    -
>
>    When partial is True, defaults are *not* applied at all. It makes zero
>    sense for defaults to pop up when you specifially indicate you're working
>    with partial data.
>    -
>
>    A switch named apply_defaults would be available to force defaults for
>    partial data or, conversely, leave them out from whole objects.
>
> Any objections?
>
> There's nothing here that couldn't be implemented on top of the current
> Schematics, but at the latest this must be sorted out when the undefined
> feature appears, and the only thing it depends on now is #359
> <https://github.com/schematics/schematics/pull/359>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/schematics/schematics/issues/360>.
>



-- 
jms dnns
me <http://jmsdnns.com> // facebook <https://www.facebook.com/jmsdnns> //
github <https://github.com/jmsdnns/> // twitter
<https://twitter.com/jmsdnns>
