### ISSUE TITLE
Is there a way I can warn when a schema is not valid?

### ISSUE THREAD

**Issue by srossross** [schematics/schematics#367]
Is there a way to provide warning rather then exceptions when validating a schema or initializing my models?

**Comment by bintoro** [comment]
No, not directly. But it would be fairly simple to write a wrapper that catches the exception and reissues it as a warning:

```python
class BaseModel(Model):
    def validate(self, partial=False, strict=False, ...):
        try:
            super().validate(partial=partial, strict=strict, ...)
        except ModelValidationError as exc:
            warn(ValidationWarning(exc.messages))
```

Do you have a use case that makes this impractical?

**Comment by srossross** [comment]
When I try that I still get a model conversion error: https://gist.github.com/srossross/fba9163d1bb4c9ad92f7

**Comment by bintoro** [comment]
Creating an instance does not automatically run validation. You're hitting a *conversion error* at the import stage, which is distinct from a validation error.

Every time you import data, you should wrap the code in a try–except construct to catch any conversion errors. Or you could override `Model.convert()` and turn the errors into warnings there.

**Comment by srossross** [comment]
Thank you
