### ISSUE TITLE
Redesign the conversion/validation exceptions

### ISSUE THREAD

**Issue by bintoro** [schematics/schematics#369]
### Unify aggregate exception classes

The current separation between `ModelConversionError` and `ModelValidationError` provides no informational value at all, since the error class is picked solely based on which model-level routine was invoked and has nothing to do with what actually went wrong.

To illustrate, the _exact same_ conversion error may appear as a `ModelConversionError` or `ModelValidationError`, depending on if you called `Model.convert()` or `Model.validate()`, respectively. This is unnecessary complexity and a potential source of confusion (#137).

Also, since these classes may represent data on _several_ errors, each of which may independently be either a conversion error or a validation error, it's clear that communicating anything about the error types through the name of the class is just not viable.

Based on this, I think the aggregate exception classes should be unified.
### Improve exception message format

Right now the aggregate error message structure only contains the names of the offending fields coupled with textual messages.

The format should be redesigned to accommodate at least the following items for each individual error:
- name of the field or index of the item (#307), whichever is applicable
- type of the error (conversion/validation)
- human-readable textual message
- structured response data from the validator/converter function (e.g., error code).

**Comment by bintoro** [comment]
I've been sketching a new exception hierarchy that looks like this:

* BaseError
  * FieldError
    * ConversionError
    * ValidationError
    * StopValidationError
  * CompoundError
    * DataError

All `FieldError` subclasses represent field-specific errors arising from the field's own validators, while errors bubbling up from substructures within compound fields are represented by a `CompoundError`.

Therefore, `FieldError.messages` is now guaranteed to be a flat list (as is currently the case for errors on basic types).

`CompoundError.messages`, on the other hand, is always guaranteed to be a dictionary, keyed by the offending item's identifier. For a `ListType`, this identifier is the item's index.

`DataError` is a `CompoundError` representing the result of validating an entire model. It's basically identical to `ModelConversionError` and `ModelValidationError`, both of which will be deprecated.

Error messages are no longer just strings but `ErrorMessage` objects containing three attributes:
  * type (conversion or validation error)
  * summary (the human-readable message)
  * info (an arbitrary value; e.g., an error code or some other response from the validator)

#### Example

```python
class M(Model):
    intfield = IntType(max_value=3)
    listfield = ListType(IntType(max_value=3))
    modelfield = ModelType('M')

inputdict = {
    'intfield': 1,
    'modelfield': {
        'intfield': 2,
        'modelfield': {
            'intfield': 3,
            'listfield': [1, 2, 3, 4, 5, 6],
            'modelfield': {
                'intfield': 4}}}}

M(inputdict).validate()
```

**Result before:**

```python
schematics.exceptions.ModelValidationError: {
  'modelfield': {
    'modelfield': {
      'listfield': [
        [u'Int value should be less than or equal to 3.'], 
        [u'Int value should be less than or equal to 3.'], 
        [u'Int value should be less than or equal to 3.']], 
      'modelfield': {
        'intfield': [u'Int value should be less than or equal to 3.']}}}}
```

**Result now:**

```python
schematics.exceptions.DataError: {
  'modelfield': {
    'modelfield': {
      'listfield': {
        3: [<ValidationError: 'Int value should be less than or equal to 3.', info=None>], 
        4: [<ValidationError: 'Int value should be less than or equal to 3.', info=None>], 
        5: [<ValidationError: 'Int value should be less than or equal to 3.', info=None>]}, 
      'modelfield': {
        'intfield': [<ValidationError: 'Int value should be less than or equal to 3.', info=None>]}}}}
```

**Comment by bintoro** [comment]
Can anyone think of a better name for `DataError`? Granted, it's accurate, as it represents a problem with the data. But it seems kinda vague. The trouble is I can't come up with a superconcept that would encompass both "validation" and "conversion".

Or maybe `DataError` is fine and I'm just too used to the old nomenclature.

**Comment by lkraider** [comment]
`DataError` sounds good to me.

**Comment by lkraider** [comment]
Regarding discussion in #445, we should have the message be a string to keep compatibility with default Exceptions (and [PEP-352](https://www.python.org/dev/peps/pep-0352/) ), and add a `.errors` attribute to hang the parseable info from.

eg:
```
class BaseError(Exception):
    def __init__(self, message, errors=None):

        # Call the base class constructor with the parameters it needs
        super(BaseError, self).__init__(message)

        # Now for your custom code...
        self.errors = errors
```

PEP-352 excerpt:
> No restriction is placed upon what may be passed in for args for backwards-compatibility reasons. In practice, though, only a single string argument should be used.

**Comment by lkraider** [comment]
I think we achieved the goal here right @bintoro ? Closing now that the patch for parsing the errors has landed in development.
