### ISSUE TITLE
Option for ignoring 'rogue' fields.

### ISSUE THREAD

**Issue by afahim** [schematics/schematics#370]
Often times, JSON responses send a large blob of information, while applications only care about a few of the fields. For instance, a Person API might send 'full_name', 'first_name', 'last_name', 'age' 'height', etc. However if my application only cares about the person's first name, and age, then I'd like to define a model in my app such as

```python
class Person(Model):
    first_name = StringType()
    age = IntType()
```

This only has the fields that I care about. In this case, if the Person API sends me extra fields, or changes its responses to add more fields, I'd like to ignore them since my application doesn't care about them. However with the current implementation of schematics, all extraneous ('Rogue') fields throw a schematics.exceptions.ModelConversionError. So I have to define all the extra fields in the model, even tho I never use them.

Is there a way of telling a model to ignore 'Rogue' fields? If not, I was thinking I could define a ModelOption that basically suppresses any Rogue Field exceptions for extraneous fields encountered in the response.

**Comment by edc** [comment]
You can pass `strict=False` to the constructor.

```python
class Person(Model):
    first_name = StringType()
    age = IntType()

Person({'x': ''})  # => raise ModelConversionError: {'x': 'Rogue field'}
Person({'x': ''}, strict=False)  # => no error
```

`import_data` also does not care about unrecognized data:

```python
Person().import_data({'x': ''})  # => No error
```

**Comment by afahim** [comment]
That's just perfect, thanks @edc!

**Comment by niltz** [comment]
This doesn't seem to work for nested models. My child models still throw rogue field exceptions

**Comment by fabouru1985** [comment]
Same from here

"

This doesn't seem to work for nested models. My child models still throw rogue field exceptions
--


"

**Comment by chiajr** [comment]
You have to set strict=False in the model. 

object = ModelType(objectA, strict=False)

hope it helps
