### ISSUE TITLE
default Options class for all Models

### ISSUE THREAD

**Issue by oryband** [schematics/schematics#381]
i'd like to be able to set default options for all of my Models, instead of redundantly re-defining them per model. Something like this:
```python
class DeafultModel(Model):
    class Options:
        serialize_when_none = False

class ModelOne(DefaultModel):
    # the above saves me from redefining `class Options` with the same options in here.
    # code

class ModelTwo(DefaultModel):
    # same
    # code
```
Is this already possible, or does this require adding support?

**Comment by bintoro** [comment]
This should work exactly as you've described. Does it not?

**Comment by oryband** [comment]
@bintoro idk, there isn't any documentation regarding "default options". i will try and close this if so.
maybe this should be added to the docs?

**Comment by bintoro** [comment]
The docs are incomplete. They're also somewhat out of date now that Schematics is under heavy development again.

**Comment by oryband** [comment]
@bintoro this does work as mentioned, thanks.
