### ISSUE TITLE
UTCDateTimeType missing from release v1.1.1

### ISSUE THREAD

**Issue by oryband** [schematics/schematics#382]
it's just not there for some odd reason

**Comment by bintoro** [comment]
v1.1.1 predates UTCDateTimeType. New users should use the development version.

**Comment by oryband** [comment]
@bintoro isn't the development version unstable? there isn't a release for it at all

**Comment by bintoro** [comment]
@oryband It's always quite stable. As long as the Travis build is passing, `development` should be safe to use.

Normally `master` shouldn't be this far behind `development`, but right now we have accumulated several breaking changes while building up to v2.0. There isn't really a point where an interim release would make a whole lot of sense; hence the gap between the two branches.

I suppose we could push a `dev` release to PyPI that wouldn't be installed automatically by `pip`.

**Comment by bintoro** [comment]
FYI, a development release `2.0.0.dev1` is now available via PyPI (with the `--pre` option).

**Comment by oryband** [comment]
@bintoro thanks will try it.

also thanks for the quick reply. keep up the good work! :)
