### ISSUE TITLE
Preserve order of keys in nested models when doing **to_primitive** ?

### ISSUE THREAD

**Issue by goanpeca** [schematics/schematics#394]
Is there a way to set the order of keys within nested models when doing `to_primitive`?

The top level model keeps the order of keys, but nested models seem to be sorted alphabetically.

**Comment by bintoro** [comment]
I'm curious, how did you manage to sort the top-level model only? The feature introduced in #297 seems to work fine for nested models, and I'm not aware of any other way of maintaining field order upon export.

**Comment by bintoro** [comment]
Closing as invalid.
