### ISSUE TITLE
ModelOptions should allow anykind of extra parameters

### ISSUE THREAD

**Issue by Guibod** [schematics/schematics#397]
Got a `TypeError: __init__() got an unexpected keyword argument 'route'` error while trying to extend the Options class from my schematics model.

``` python
class Search(Model):
    uuid = UUIDType(required=True)
    revision = NumberType(required=True)
    created_at = DateTimeType(default=datetime.datetime.now)
    updated_at = DateTimeType(default=datetime.datetime.now)

    class Options:
        route = 'my_flask_route_name'
        namespace = 'searches'
        roles = {}
```

I guess that I can start my own implementation of `ModelOptions` and alter my `__optionsclass__` but that sucks.
Could you please allow an `extra` field that allow us to put all kind of stuff in the model Options ?

**Comment by bintoro** [comment]
I totally agree.

The options code currently seems to special-case members starting with "_", but it doesn't actually set them on the hidden `_options` object:

```python
>>> class Foo(Model):
...     class Options:
...         _test = 123
... 
>>> Foo.Options._test
123
>>> Foo._options._test
AttributeError
```

I believe the original intent is just to skip `__special__` attributes. But we could build on this and allow custom members beginning with an underscore and only skip those that are *actually* special.

**Comment by rmb938** [comment]
See pull #449 for the implementation of @bintoro 's comment.
