### ISSUE TITLE
Move to a single-branch setup?

### ISSUE THREAD

**Issue by bintoro** [schematics/schematics#401]
What's the point of having two permanent branches? We could just work on `master` and tag releases along the way.

Thoughts?

**Comment by lkraider** [comment]
The idea is that master is stable vs development ([git-flow](http://nvie.com/posts/a-successful-git-branching-model/)). But if it makes it simpler for people to contribute having a single branch I have nothing against it ([github-flow](https://guides.github.com/introduction/flow/)). Another option is move development to master and have production branches out of master ([gitlab-flow](https://about.gitlab.com/2014/09/29/gitlab-flow/)).

**Comment by bintoro** [comment]
I articulated my question poorly. I wanted to discuss the merits of a two-branch model in the context of *this particular project*.

A separate development branch is mainly useful only if there's a need to commit patches to the current stable release while the development branch is unstable or too far diverged. I'm pretty sure this has never happened in the history of Schematics.

Moreover, if a need for a long-lived release branch should arise, one can be created at any time.

The current effort to come up with v2.0 would have been an excellent candidate for work that happens on its own branch, but by then `development` had already become the de facto mainline branch.

I'm hoping that, once 2.0 is ready, we could release way more often. Having a redundant master branch around just causes extra noise due to the back-and-forth merges between the two.

**Comment by lkraider** [comment]
Let's move on with github-flow from 2.0 onwards then.

Keep this issue open until development branch can be deleted after release.

**Comment by kracekumar** [comment]
+1 to move to github workflow.

**Comment by lkraider** [comment]
Code has been moved to `master` default, and `development` has been pruned.

I also enabled branch protection on master to require tests to pass before merge.

**Comment by lkraider** [comment]
Ok, it seems deleting the development branch while PRs were still open was not a good idea (it closes them). I've since reverted the branch and reopened the PRs.
