### ISSUE TITLE
Any chance of a new pip build?

### ISSUE THREAD

**Issue by hunt3ri** [schematics/schematics#403]
Hi this existing dev2 pip build contains a number of bugs that have been fixed recently.  Any chance of a new build??

Thanks
Iain

**Comment by sheilatron** [comment]
+1

**Comment by bintoro** [comment]
Apologies for this taking so long. Pre-release 2.0.0.alpha is now available on PyPI.

**Comment by sheilatron** [comment]
Thanks @bintoro !

**Comment by j2labs** [comment]
aww yiss!!

On Wed, May 4, 2016 at 9:02 PM, Sheila Allen <notifications@github.com>
wrote:

> Thanks @bintoro <https://github.com/bintoro> !
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/schematics/schematics/issues/403#issuecomment-217050604>
>



-- 
jms dnns
me <http://jmsdnns.com> // facebook <https://www.facebook.com/jmsdnns> //
github <https://github.com/jmsdnns/> // twitter
<https://twitter.com/jmsdnns>

**Comment by hunt3ri** [comment]
Many thanks @bintoro upgraded today :+1:
