### ISSUE TITLE
flatten / expand

### ISSUE THREAD

**Issue by bintoro** [schematics/schematics#408]
What's the use case for `flatten()` and `expand()`? Do we want to keep them?

`ListType` has a weird feature specifically to support `expand`: it accepts dictionaries and uses their keys to sort the values. This is so that the list

```
field = ['foo', 'bar']
```

can be flattened into

```
{'field.0': 'foo', 'field.1': 'bar'}
```

and successfully expanded without confusing it with a dictionary with keys 0 and 1.

I'm not okay with `ListType` accepting dictionaries. To work around this, I taught `expand` to interpret a flattened structure with a zero-based key sequence as a list. This works, but it means that a legitimate dictionary with (only) zero-based integer keys will also become a list on expansion. Is this good enough? Does anyone use `flatten`?

The alternative is to rewrite `expand()` so that it actually looks at the model it's expanding to, but I don't want to go there if this is just a vestigial feature that no one uses.

**Comment by jmsdnns** [comment]
This was introduced by @jokull's team at Plain Vanilla to help with caching objects somehow, iirc.

**Comment by bintoro** [comment]
One situation where these things could be useful is when you have a nested dict of validation errors and want to respond with dot-separated paths that point to the invalid items.

I suppose the functions are worth preserving. The format can probably be tweaked a bit without too much breakage. Representing lists as

```
{'field[0]': 'foo', 'field[1]': 'bar'}
```

would eliminate the need to guess the datatype.

**Comment by bintoro** [comment]
Given that these functions only serve some *very* niche purpose (if any at all), I've concluded that maintaining them within the core library isn't warranted.

One can munge dictionaries in a variety of ways. It's not clear why Schematics should provide this specific algorithm, when it's barely related to the rest of the library and has no general utility.

If anyone disagrees, please reopen.
