### ISSUE TITLE
default validation context should add a oo item

### ISSUE THREAD

**Issue by omgq** [schematics/schematics#415]
```python
from schematics.models import Model
from schematics.types import IntType, StringType
from schematics.types.compound import ModelType


class SomeModel(Model):
    intt = IntType(required=True)
    strt = StringType(required=True)
    
ModelType(SomeModel, required=True).validate({"intt":1, "strt": "abcd"})

```

See python code above. It would raise exception as following:
```python
.../schematics/types/compound.pyc in _convert(self, value, context)
    124             raise ConversionError(
    125                 "Input must be a mapping or '%s' instance" % self.model_class.__name__)
--> 126         if context.convert and context.oo:
    127             return model_class(value, context=context)
    128         else:

AttributeError: 'Context' object has no attribute 'oo'
```
After tracing back, it seems the default validation context misses an item "oo".

```python
.../schematics/validate.py

def get_validation_context(**options):
    validation_options = {
        'field_converter': validation_converter,
        'partial': False,
        'strict': False,
        'convert': True,
        'validate': True,
        'new': False,
--->    'oo': False
    }
    validation_options.update(options)
    return Context(**validation_options)
```

Inserting the line above solves the problem.

**Comment by bintoro** [comment]
@omgq That's not the correct way to use Schematics. You want something like this instead:

```python
m = SomeModel({"intt":1, "strt": "abcd"})
...
m.validate()
```

Or, to validate immediately as you load the data:

```python
m = SomeModel({"intt":1, "strt": "abcd"}, validate=True)
```

Or, using the functional API (without instantiating the model):

```python
from schematics.validate import validate

validate(SomeModel, {"intt":1, "strt": "abcd"})
```

**Comment by omgq** [comment]
@bintoro I see, thanks. 
BTW, may I ask what's the intention for the "oo" in context, which exists in import_context but not validation_context?

**Comment by bintoro** [comment]
It's a flag indicating that the process was initiated from a model instance. It controls the behavior of submodels: if you're importing into a dictionary using the functional API, submodels will be imported as dictionaries as well. Conversely, using `Model.__init__` will recursively instatiate submodels too.

In fact, the flag *should* be present in the default validation context. The thing is, it only matters when you initiate the validation process from a standalone type. That is not yet officially supported usage, so it lacks testcases, as evidenced by the error you got.

**Comment by omgq** [comment]
@bintoro Thanks for the explanation.
