### ISSUE TITLE
Minor wheel issues: license and author files missing from wheel

### ISSUE THREAD

**Issue by pombredanne** [schematics/schematics#420]
In #116 a license file was added, but it is not included in the built wheels.
In that license the AUTHORS files is referenced. And it is not included either in the wheel.
Finally the DESCRIPTION.rst of the wheel is empty because the `long_description` in not setup.py's  `setup()

**Comment by bintoro** [comment]
Adding `long_description` is on the to-do list.

As for LICENSE and AUTHORS, I need some clarification. As you know, wheel is a built format, so it generally only contains stuff that goes into the install directory. Where exactly would you expect these files to show up?

**Comment by pombredanne** [comment]
There is unfortunately only provision for a single LICENSE file, as you can see here:
https://bitbucket.org/pypa/wheel/issues/138/include-more-than-one-license-file-or
@dholth this is a typical use case for more than a single file BTW

@bintoro for now the option would be IMHO:
1. create setup.cfg with this section
```
[metadata]
license_file = LICENSE
```
2. modify the LICENSE file to avoid referring to the AUTHORS files and at build time (painful custom setup modification) concat the license and AUTHORS file in one file. OR do not include at all AUTHORS in the built wheel.

Note that if you do not include the license in your wheel, you are basically making it hard for every users of this wheel to comply: the wheel would not meet you licensing requirements to contain the license... hence every user is de-factor not compliant.

**Comment by bintoro** [comment]
Interesting. I did not know about the `license-file` option. The labyrinthine world of Python packaging never ceases to surprise!

But yeah, let's do this. We don't need to refer to AUTHORS from LICENSE — the license file can easily be made self-contained.

**Comment by pombredanne** [comment]
> The labyrinthine world of Python packaging never ceases to surprise! 
This is a fair comment for the past, but things are really much better these days and improving!

**Comment by lkraider** [comment]
Sorry, missed this one for 2.0.0, but just made the changes and added to master, next release should include the LICENSE file!

**Comment by lkraider** [comment]
FYI: v2.0.1 just released and contains the LICENSE file.
