### ISSUE TITLE
Update Model instance with raw_data

### ISSUE THREAD

**Issue by alexhayes** [schematics/schematics#423]
I have a model that looks similar to as follows;

```python
class MyModel(Model):
    ....
    ....

    def save(self):
        raw_data = call_restful_api_thing(self.to_primitive())
        # Update model instance to that of raw_data
```

To update the model instance is it safe to simply do the following;

```python
    def save(self):
        raw_data = call_restful_api_thing(self.to_primitive())
        self.__init__(raw_data)
```

I mean, at the moment it works, but it's potentially not future proof and perhaps not very intuitive.

I'm not really interested in setting the values manually because it's a deeply nested structure and it would be a bit of a pain, not easily maintainable and certainly not DRY.

**Comment by bintoro** [comment]
If you're looking to completely replace the data on the instance, then `__init__()` is indeed the right choice. But if you want to perform an *update*, overwriting only certain fields, there's `import_data()` for that.

In the v2.0 development version, `import_data` takes a `recursive` boolean option. When `True`, the data in submodels will also be merged. When `False` (the default), it works like `dict.update()`.

**Comment by alexhayes** [comment]
Great thanks!
