### ISSUE TITLE
New project named itself similarly

### ISSUE THREAD

**Issue by kstrauser** [schematics/schematics#432]
A new project, [schemagic](https://github.com/Mechrophile/schemagic), is a data validation library for Python. I wish they'd picked almost literally any other name. :-/

**Comment by lkraider** [comment]
We can't expect there won't be similar ones popping up all the time. In the end it's the user adoption that make a project popular and the name known.

**Comment by kstrauser** [comment]
I'd meant this more as a "calling attention to" kind of message. While I agree with your point, should we maybe kindly ask them to consider renaming before they've become widely established to avoid confusion?

**Comment by j2labs** [comment]
Imitation is the sincerest form of flattery.
It will surely emerge that our projects have similar names. The history and value of this one will speak for itself nicely, but I certainly encourage saying hello.
Perhaps they'd be interested in joining the effort here?
Also, this project would be called "structures" if someone didnt take that name first, causing me to think some more and eventually pick "schematics" :)

jms dnns




On Tue, Jul 5, 2016 at 6:34 PM -0400, "Kirk Strauser" <notifications@github.com> wrote:












I'd meant this more as a "calling attention to" kind of message. While I agree with your point, should we maybe kindly ask them to consider renaming before they've become widely established to avoid confusion?
