### ISSUE TITLE
Set is not a valid type for `choices` parameter

### ISSUE THREAD

**Issue by di** [schematics/schematics#433]
Using:

``` console
$ pip freeze | grep schematics
schematics==1.1.1
$ python --version
Python 2.7.10
```

And the following class:

``` python
from schematics.models import Model
from schematics.types import StringType

class Foobar(Model):
    foo = StringType(choices={'foo', 'bar'})
```

This raises a `TypeError`:

```
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    class Foobar(Model):
  File "test.py", line 5, in Foobar
    foo = StringType(choices={'foo', 'bar'})
  File "/private/tmp/env/lib/python2.7/site-packages/schematics/types/base.py", line 339, in __init__
    super(StringType, self).__init__(**kwargs)
  File "/private/tmp/env/lib/python2.7/site-packages/schematics/types/base.py", line 184, in __init__
    raise TypeError('"choices" must be a list or tuple')
TypeError: "choices" must be a list or tuple
```

Is there a reason why `choices` must be an ordered collection?

Furthermore, this seems to be a regression, as this behavior was supported in `schematics<=1.0.2` and removed with https://github.com/schematics/schematics/pull/267

**Comment by chadrik** [comment]
Hi @di I believe I introduced this issue when I added support for passing a callable to `choices`.  I'll change this to test if the choices object is iterable.

**Comment by promptworks-integrations** [comment]
Hi @chadrik, checking if the choices object is iterable is not enough, since strings are also iterable. 

I have two open PRs (#434 and #436, wasn't sure which branch is preferred) which should solve this issue.

**Comment by di** [comment]
Hi @chadrik, checking if the choices object is iterable is not enough, since strings are also iterable.
I have two open PRs (#434 and #436, wasn't sure which branch is preferred) which should solve this issue.

**Comment by lkraider** [comment]
Merged 436, thanks for the PR.
