### ISSUE TITLE
Failure to parse a valid ISO8601 / RFC3339 Date Time string

### ISSUE THREAD

**Issue by nochristrequired** [schematics/schematics#437]
Hi, I'm getting the following error

> schematics.exceptions.ModelConversionError: {'items': {'created_at': [u'Could not parse 2016-07-29T14:18:16.706000+00:00. Should be ISO8601.'], 'updated_at': [u'Could not parse 2016-07-29T14:18:39.692000+00:00. Should be ISO8601.']}}

As far as I can tell, the date time strings above are valid ISO8601 and conform to the internet datetime standard. The following can process these date time strings perfectly fine.

``` python
import dateutil.parser
dateutil.parser.parse('2016-07-29T14:18:16.706000+00:00')
```

Thanks!

**Comment by bintoro** [comment]
Schematics v1 doesn't understand time zones apart from the "Z" designator. In v2 your example works.

**Comment by nochristrequired** [comment]
This is the first mention I've seen of a v2 release. Interesting.

**Comment by lkraider** [comment]
2.0.0 now on PyPI:
https://pypi.python.org/pypi/schematics/2.0.0
