### ISSUE TITLE
Parsing exception messages in 2.0.0a1

### ISSUE THREAD

**Issue by synic** [schematics/schematics#445]
In 1.x, validation error exceptions could be returned directly to the client.  Now they are in the format:

```
DataError({'email': [ErrorMessage("A calendar with the email address "jasonmartinez@nichols.org" already exists in the system.")]},)
```

If there's a `ModelType` field on the model, the error messages can even come with embedded `ValidationError` classes in it, like so:

```
{'credentials': {'oauth2_credentials': ValidationError("Invalid credentials supplied.")}}
```

Are there any current methods for making these easier to deal with?  How is it expected we'll convert these error messages?

**Comment by neilalbrock** [comment]
I'd also like some clarification on this... I've previously used schematics to model and validate API calls and the 1.x handling of errors made it simple to return those in JSON format to the consumer on error.

In 2.x I'm having to write some fairly byzantine code to handle getting from the new error format to something that can be serialised to JSON. This is a retrograde step in my opinion, so at least providing a new equivalent to the old errors block would simplify things again.

Schematics makes doing fairly complex things nice and simple, be good to try and keep it that way.

**Comment by rmb938** [comment]
I would like to easily convert these errors to JSON as well.

**Comment by synic** [comment]
I worked around it by creating a custom JSONDecoder that basically calls `str` on anything it doesn't recognize:

```python
import json

class ExceptionJSONEncoder(json.JSONEncoder):
    """Format the error messages we get from schematics.
    I think the format of their error messages is currently bugged, I reported
    it here: https://github.com/schematics/schematics/issues/445
    Hopefully this class is just temporary.
    """
    def default(self, obj):
        return str(obj)
```

Then you can do something like `json.dumps(data, cls=ExceptionJSONEncoder)`.  It works, but it's definitely not ideal.

**Comment by neilalbrock** [comment]
I ended up with this:

```python
def serialize_errors(errors):
    """Serialize Schematics 2.x Errors"""
    if isinstance(errors, dict):
        res = {}

        for k,v in errors.iteritems():
            if isinstance(v, basestring):
                res[k] = v
            elif isinstance(v, list):
                res[k] = [m.summary for m in v]
            elif isinstance(v, dict):
                res[k] = serialize_errors(v)
            else:
                res[k] = [m.summary for m in v.messages]

        return res

    else:
        return errors
```

I'll give the JSON encoder version a try, might be simpler. Although I wonder if this version might allow for serializing to XML too?

**Comment by bintoro** [comment]
I'm glad this has generated some discussion. Before embarking on the rewrite, I opened #369 but got no comments there.

The reason for turning error messages into something more complex than just strings is my belief that strings are inadequate representations of error items.

Consider:

```
"The value should be greater than or equal to 5."
```

vs

```
{
    "constraint": "NUMBER_GTE",
    "parameter": 5,
}
```

The latter is obviously easier to parse.

Sure, in some situations we can simply pass on the English-language string and be done with it, but I think the structured approach is much better when building APIs and localized applications. Or what do you guys think?

That said, we could certainly include a utility to perform practical transformations on an error object, such as the ability to convert nested objects into Python primitives. Another one that I've thought about before is something to turn the tree into a series of JSON Pointer -like paths to the invalid items.

**Comment by rmb938** [comment]
A possibility would to follow the jsonapi errors format found here: http://jsonapi.org/format/#errors

That way the errors would follow as well known format.

**Comment by lkraider** [comment]
I like the idea of using a standard format in an `errors` property for the exception.

The `message` property should be a string, please see my comment regarding PEP-352: https://github.com/schematics/schematics/issues/369#issuecomment-265921709

**Comment by lkraider** [comment]
Thanks to @toumorokoshi patch, errors now can be serialized with a `to_primitive` call, and the string representation already defaults to that:

```python
>>> except DataError as e:
>>>    print(e)
{"location": {"country_code": ["String value is too long."], "gps": ["This field is required."]}}

>>>    print(e.errors)
{'location': {'country_code': ValidationError([ErrorMessage(u'String value is too long.', None)]), 'gps': ConversionError([ErrorMessage(u'This field is required.', None)])}}
```

Code is merged in development, so I'm closing here now. Thanks for all the ideas and please open a new issue if want to propose other improvements!
