### ISSUE TITLE
2.0.0 Defaults, not copied but using reference

### ISSUE THREAD

**Issue by Guibod** [schematics/schematics#451]
I having issue porting my v1 project to v2 project. If I instanciate an object using 

```
model = MyModel()
```

rather than 

```
model = MyModel({})
```

I end up using defaults as reference and not copy. Ending with all subsequent objects to inherit their sibling value as default.

```
import unittest

from schematics import Model
from schematics.types import ListType, StringType

class MyModel(Model):
    items = ListType(StringType, default=[])


class TestIterable(unittest.TestCase):
    def test_without_value(self):
        model = MyModel()
        model.items.append('foo')
        model.items.append('bar')

        self.assertEqual(len(model.items), 2)

        model2 = MyModel()
        self.assertEqual(len(model2.items), 0)  # This won't work. DUH. 

    def test_with_value(self):
        model = MyModel({})
        model.items.append('foo')
        model.items.append('bar')

        self.assertEqual(len(model.items), 2)

        model2 = MyModel({})
        self.assertEqual(len(model2.items), 0)
```

**Comment by Guibod** [comment]
I really don't know what it implies for my model, I can't help but wonder if I need to replace every single object instantiation by the `MyModel({})` variant to avoid problems.

**Comment by rmb938** [comment]
I just ran into this issue as well, it seems like a major oversight and is causing a lot of issues.

**Comment by bintoro** [comment]
> ```python
> items = ListType(StringType, default=[])
> ```

You should never do that unless you want all instances to get a copy of the same list. Instead, you should pass the constructor (`list`):

```python
items = ListType(StringType, default=list)
```

This is not specific to v2.0. It has always been this way.

**Comment by rmb938** [comment]
That doesn't work though if I need to default to a list or dict with actual data.

**Comment by bintoro** [comment]
> That doesn't work though if I need to default to a list or dict with actual data.

Sure it does; simply pass a function that returns whatever object you wish:

```python
items = ListType(StringType, default=lambda: [1, 2, 3])
```

Given a default of `[]`, which is mutable, it may seem like the right thing to do would be to create a copy instead of reusing the same object. But there is no general way of making this decision, and that's why a factory function is a necessity.

This also happens to be exactly how Python's own [defaultdict](https://docs.python.org/3/library/collections.html#collections.defaultdict) works.

**Comment by rmb938** [comment]
Ah yes, forgot about lambdas. Thanks that seems to be working now!

**Comment by Guibod** [comment]
Thanks, applied that to my project.
