### ISSUE TITLE
Release 2.0

### ISSUE THREAD

**Issue by sirex** [schematics/schematics#455]
I see, that 2.0 is still in alpha stage, latest version is `2.0.0a1`.

What is missing for this to be released as final stable 2.0?

**Comment by synic** [comment]
Seems like the project might be dead.  There are issues that have had no response, no updates in months.

**Comment by bintoro** [comment]
Nope, I've just been occupied with actual paid work for a few months, but I'm looking into the outstanding issues right now.

I wish I could set aside a couple a weeks to focus solely on this project. There's not really that much left to do before 2.0 can be shipped.

**Comment by rskumar** [comment]
its  a nice and really useful project, would be very sad if it dies :(

**Comment by harlowja** [comment]
Perhaps you could add interested folks as reviewers/commiters on github, then people can continue with making changes without forking (or other).

**Comment by aadis** [comment]
We're currently starting a new code base, and are evaluating if we should use 1.1 or directly jump into 2.0. Happy to contribute fixes back.

Can we get a summary of 1.x to 2.0 changes, to help us evaluate?

**Comment by toumorokoshi** [comment]
@bintoro @lkraider can someone start the process on releasing a non-alpha 2.0 build?

We may also want to release the new version as Beta, since so many aspects of the errors were modified.

**Comment by lkraider** [comment]
I agree, we can checkpoint a beta right now.

I am merging #431, so only one tagged issue remains for 2.0 release:
https://github.com/schematics/schematics/milestone/3

**Comment by toumorokoshi** [comment]
@lkraider is 2.0 good for an official release? So excited!

**Comment by lkraider** [comment]
It is.

@bintoro I can release it on PyPI if you add me there.

**Comment by lkraider** [comment]
@bintoro I do, thanks. I'll prepare the release of 1.1.2 and 2.0.

**Comment by lkraider** [comment]
2.0.0 now on PyPI:
https://pypi.python.org/pypi/schematics/2.0.0
