### ISSUE TITLE
Opaque Type

### ISSUE THREAD

**Issue by jdandrea** [schematics/schematics#467]
Suppose I have a model, and one of the fields is an opaque dictionary we'll call "parameters".

Each value can be a string/number or a list, or a dictionary. Lists and dictionaries can also be of arbitrary depth and contain strings/numbers ... or more lists/dictionaries. There is no particular validation of the strings/numbers here, other than the requirement for arbitrary nesting support.

How do I declare this using schematics, in particular accounting for nested lists/dictionaries? I was thinking along the lines of a self-referential type, where one of the possibilities could be itself.

**Comment by bintoro** [comment]
Perhaps we should implement an explicit `AnyType`. But you can just use `BaseType` and it should work, I think.

Or... do you want to validate the value, but only if it's a string or a number? I'm not 100% sure what you're asking.

**Comment by jdandrea** [comment]
I'd like to be able to validate that a value is simply a dictionary or a list, regardless of its contents (what I'm meaning here by "opaque").

**Comment by bintoro** [comment]
Good point. It would be nice to be able to specify a compound type with no inner type at all.

What I was trying to say in my previous comment was that you can achieve the desired behavior with, e.g., `ListType(BaseType)`, since `BaseType().validate()` always passes.

**Comment by jdandrea** [comment]
Oh! If there's a way for me to do it in the interim, that would be fantastic. I think I see what you mean now. Thanks for that example. I'll give it a try.

**Comment by lkraider** [comment]
If something like `ListType(BaseType)` works, I'd accept a PR setting it as the default.
