### ISSUE TITLE
Validators with db connection

### ISSUE THREAD

**Issue by lvalladares** [schematics/schematics#469]
Im creating a DB schema for mongo validation using pymongo and i want to do some complex validation against my database, i want to check some constraints like uniqueness of some fields so i create my own methods inside my class, something like this:

```
class Producto(Model):
    codigo = StringType(min_length=2, max_length=20, required=True)
    ........

    def validate_codigo(self, data, value):
        elemento = db.facturas.find({'productos.codigo': {"$eq": data["codigo"]}}).count()
        if elemento > 0:
            raise ValidationError(T("Already exists"))
```

That dont work because the validate_codigo function dont know the db variable, how i can pass the variable to this method? there is anyway to pass aditional parameter to the .validate()?

**Comment by kracekumar** [comment]
In development branch `validate` takes `app_data` and `kwargs`. I'm not sure `context` or `app_data` is available inside `validate_`. Probably @bintoro and @lkraider can add more.

One workaround is to create a `db` field in `Producto` and access that inside `validate_codigo`. Example

```python
In [49]: class Test(Model):
    ...:     file_to_write = StringType(min_length=1, required=True)
    ...:     name = StringType(min_length=1, required=True)
    ...:     def validate_name(self, data, value, **kwargs):
    ...:         # call super
    ...:         with open(data['file_to_write'], 'w') as f:
    ...:             f.write(value)
    ...:             

In [50]: t = Test({'file_to_write': '/tmp/foo', 'name': 'Python'})

In [51]: t.validate()

In [53]: open('/tmp/foo').read()
Out[53]: 'Python'

```

**Comment by bintoro** [comment]
Yeah, in v2.0 the `context` parameter is supported in validators as well:

```python
class Producto(Model):

    def validate_codigo(self, data, value, context):
        db = context['app_data']['db']

...

instance.validate(app_data={'db': db_object})
```

**Comment by lkraider** [comment]
Also, in #466 , you can access the `self` instance.

**Comment by lkraider** [comment]
2.0.0 now on PyPI:
https://pypi.python.org/pypi/schematics/2.0.0
