### ISSUE TITLE
Dangerous performance issue with ModelConversionError in nested models

### ISSUE THREAD

**Issue by petee-d** [schematics/schematics#470]
There is a very old change by @ryanolson in current master (1.1.1) which may cause critical performance issues when a ModelConversionError occurs in a deeply nested model. **This issue may cause the process to get stuck for a very long time and may be misused to starve workers on an application.**

https://github.com/schematics/schematics/blob/master/schematics/transforms.py#L108
https://github.com/schematics/schematics/blob/master/schematics/transforms.py#L415

The pattern used on both places seems to be designed to catch TypeError occurring when the called function/method doesn't expect the `mapping` kwarg, in order to call it without it. I suppose this was made to avoid adding the `mapping` kwarg to all related defs. But it has a huge issue - it is too broad and also catches ModelConversionError and possibly other errors. When a conversion error is caught, the call is retried without the mapping argument, converting the entire model again. Since two such `except`s are encountered for each level of nested models, the resulting complexity is **2^(2*N), where N is the depth of a model at which the conversion error occurred**. The application I'm working on can easily reach 10 levels of model nesting or more, so a conversion error there may be raised over a million times!

I added a pull request with a test that fails while this bug is still present:
https://github.com/schematics/schematics/pull/471/files
Note that if the `assert` is removed, the test might run for months if not killed...

An obvious fix is changing the `Exception` on these two places to a `TypeError`, but a `TypeError` could be caused due to some other reason. A better solution is adding the `mapping` kwarg everywhere it needs to be, but there may be compatibility issues with custom schematics extension (like an application I'm working on has, I went with this solution anyway). If it is deemed to be the best solution, I'll make a PR for that too.
(https://github.com/petee-d/schematics/pull/1/files)

**Comment by lkraider** [comment]
This was changed in 2.0 (current develop branch), we need to verify if recursion is still an issue.

**Comment by petee-d** [comment]
Yes, I'm well aware and although I haven't tried, I don't think it is. But personally I viewed this as a security issue (worker locking) and hotfixed this in the application promptly by using a schematics fork. So I think releasing this as (a part of, possibly) 1.1.2 might be worthwhile.

**Comment by lkraider** [comment]
Creating a 1.1.2 that fixes this makes sense. Adding `mapping` to the functions seems sensible, but what about custom types?

Another option s checking with `inspect.getargspec` inside the except block, such that we can identify the cause exactly. What do you think?

**Comment by petee-d** [comment]
Yes, I realize adding `mapping` everywhere is not ideal due to custom types. People should ideally catch unexpected stuff to `*args` and `**kwargs` when creating a custom type but I'm sure not everybody does it.

In my opinion, introspection is quite dirty, may be error prone and not that efficient... So I'd instead go with adding an attribute like `_supportsMappingArg = True` to native types that expect it and checking it with `getattr` when deciding what arguments to pass in the calls. Sure this would still break custom types expecting the `mapping` arg, but I find it very unlikely anyone uses it and if they do, they sure have at least some tests covering deserialization and will find out when upgrading the library.

If you'd rather prefer going with introspection though, fine with me!

**Comment by lkraider** [comment]
I've proposed a fix on #478 can you confirm it works for you?

**Comment by petee-d** [comment]
Sorry for the delay. The fix looks OK, much cleaner than I thought it would be. I approved the PR, thanks for fixing it!

**Comment by lkraider** [comment]
Fix applied to `master` and ready for release. Thank you for your help!

Closing here for now, pending release to PyPI: #479
