### ISSUE TITLE
Error when import TimestampType

### ISSUE THREAD

**Issue by Garlandal** [schematics/schematics#480]
when i import TimestampType from schematics, i got an error below

<img width="645" alt="screen shot 2017-04-07 at 6 18 01 pm" src="https://cloud.githubusercontent.com/assets/5059197/24796211/aaaa4aac-1bbe-11e7-92d7-f6b5541ca3d8.png">

I did not get much information about TimestampType on [doc](https://schematics.readthedocs.io/en/latest/api/types.html),
 how can i import TimestampType in right way?

**Comment by lkraider** [comment]
Hi @Garlandal try it like this:
```python
from schematics.types.temporal import TimeStampType
```

You can check the source code for this type here:
https://github.com/schematics/schematics/blob/v1.1.1/schematics/types/temporal.py#L16

**Comment by Garlandal** [comment]
@lkraider thx a lot !!!
