### ISSUE TITLE
Deprecated fields?

### ISSUE THREAD

**Issue by danqing** [schematics/schematics#490]
I'm not sure if this is new to 2.0.0, but I'm getting some deprecated warnings and I can't really find how to get rid of them:

```
env/lib/python3.6/site-packages/schematics/transforms.py:105: DeprecationWarning: Call to deprecated function _valid_input_keys.
  all_fields = schema._valid_input_keys
env/lib/python3.6/site-packages/schematics/transforms.py:251: DeprecationWarning: Call to deprecated function _options.
  if schema._options.export_order:
env/lib/python3.6/site-packages/schematics/deprecated.py:59: DeprecationWarning: Call to deprecated function _options.
  return super(class_property, self).__get__(type, type)
env/lib/python3.6/site-packages/schematics/deprecated.py:59: DeprecationWarning: Call to deprecated function fields.
  return super(class_property, self).__get__(type, type)
env/lib/python3.6/site-packages/schematics/deprecated.py:60: DeprecationWarning: Call to deprecated function _fields.
  return super(class_property, self).__get__(instance, type)
```

I wasn't really doing anything, just:
 
```py
class Status(Entity):
    # some schematics entity
    ...

Status({'key': 'value'})
```

Is there a way to not use the deprecated methods? Thanks!

**Comment by lkraider** [comment]
Hi, the internal API is changing but not all methods have been adapted, so the library itself calls the old methods. These should only appear if you run python passing in the -W parameter (example `python3.6 -W d app.py`). How are you running your code?

**Comment by danqing** [comment]
I'm running tests with `py.test`. I can mute the warnings with `--disable-pytest-warnings` but this will mute other warnings too.

Any ETA for cleaning up the internals? :)

**Comment by lkraider** [comment]
No ETA yet, but I've updated the warning to have its own class `SchematicsDeprecationWarning`, you can silence Schematics only warnings by using a category filter like this now:

```python
warnings.simplefilter('ignore', SchematicsDeprecationWarning)
```

**Comment by danqing** [comment]
Thanks @lkraider !

**Comment by soulomoon** [comment]
how do I install a global simplefilter? Seems it still warns as I add it in module level in unittest
