### ISSUE TITLE
bug in base.py:394: str only takes one arg

### ISSUE THREAD

**Issue by e271828-** [schematics/schematics#493]
@bintoro git blame says this is yours :)

`return str(value, 'utf-8')
`

should presumably be:

`return str(value).decode('utf-8')
 `

**Comment by bintoro** [comment]
`str` does take an `encoding` argument in Python 3. So does `unicode` on Python 2 (`str` is an alias for `unicode` in Schematics when running on Py2; see `compat.py`). Does the code actually fail in some situation?

**Comment by e271828-** [comment]
@bintoro You're absolutely right: this was a Python 2 issue caused by isolated testing while figuring out how to pass context into a custom type. `compat.py` wasn't being pulled in, so when I examined `str()` it had a normal function signature.
