### ISSUE TITLE
ListType throws error on Model validation

### ISSUE THREAD

**Issue by Gehbrial** [schematics/schematics#507]
```
from schematics.models import Model
from schematics.types import NumberType

class Validator(Model):
    test = ListType(NumberType, required=True, min_size=1)

Validator({"test": [1, 2, 3]}, strict=False).validate()
```

The code above throws the following error:
`TypeError: isinstance() arg 2 must be a class, type, or tuple of classes and types`

Did I miss anything? I wasn't able to find answer in the documentation.

**Comment by lkraider** [comment]
Hello,

NumberType is an abstract class, you need to specify if you are testing for ints, floats or decimals using IntType, FloatType or DecimalType instead.
