### ISSUE TITLE
How to create fields dinamically?

### ISSUE THREAD

**Issue by gabisurita** [schematics/schematics#512]
Given a model subclass, how can one add fields dynamically? I wish I could do something like:

```python
from schematics import models, types

class MyModel(models.Model):
    static_field = types.StringType()


MyModel.dynamic_field = types.IntType()
my_instance = MyModel(dict(static_field='Foo', dynamic_field=42))
```

Is there any know API methods to do so?

**Comment by lkraider** [comment]
It is possible, there is no public API, but this should work:

```
from schematics import schema, models

def append_field(cls, key, type_):
    cls._schema.append_field(schema.Field(key, type_))
    setattr(cls, key, models.FieldDescriptor(key))


append_field(MyModel, 'dynamic_field', types.IntType())
```

**Comment by gabisurita** [comment]
@lkraider works! Thanks!

I would be nice to have this documented somewhere.

**Comment by lkraider** [comment]
I'll look into adding it as a public API, it has come up before and the rework with the Schema makes this doable.

**Comment by rok-povsic** [comment]
This is great as it enables me to add fields named with reserved words such as `from`. Or is there any other (better) way to add such fields?

**Comment by lkraider** [comment]
You can use the `serialized_name` option:

```python
class Player(Model):
     id = IntType()
     _from = StringType(serialized_name='from')
```
