### ISSUE TITLE
Incorrect documentation RE: BaseType's serialize_when_none arg

### ISSUE THREAD

**Issue by tommyzli** [schematics/schematics#513]
The [docstring](https://github.com/schematics/schematics/blob/v2.0.0.dev2/schematics/types/base.py#L144-L146) for the `BaseType`  indicates that the default value for the `serialize_when_none` argument should be `True`, but in the code it is actually [`None`](https://github.com/schematics/schematics/blob/v2.0.0.dev2/schematics/types/base.py#L168). The [documentation](https://schematics.readthedocs.io/en/latest/api/types.html?highlight=serialize_when_none#schematics.types.base.BaseType) is also inconsistent; the class definition accurately indicates that the default is `None`, but the expanded parameter definitions below still say it's default is `True`.

**Comment by lkraider** [comment]
Thanks for the report, the documentation needs real love. All help is welcome.

**Comment by tommyzli** [comment]
I'd be glad to contribute, if you can point me to where the documentation is generated from - the files in the `docs/` folder don't seem to match the readthedocs site.

**Comment by lkraider** [comment]
You can edit the ones from the docs folder.

The site is pulling from the old development branch which has been removed.

@bintoro can you edit the settings there to build the docs from master, or add me there so I can do it?
