### ISSUE TITLE
Deprecated code is used internally

### ISSUE THREAD

**Issue by cmonfort** [schematics/schematics#521]
It seems that schematics V2.0.1 is using deprecated calls internally...

```bash
$ PYTHONWARNINGS=default python
Python 3.5.2 (default, Nov 17 2016, 17:05:23) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from schematics.models import Model
/home/christian/.virtualenvs/inventory3/lib/python3.5/site-packages/schematics/validate.py:118: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
  if len(inspect.getargspec(func).args) < argcount:
/home/christian/.virtualenvs/inventory3/lib/python3.5/site-packages/schematics/types/union.py:13: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
  args.update(inspect.getargspec(cls.__init__).args[1:])
>>> from schematics.types import StringType, URLType
>>> class Person(Model):
...     name = StringType(required=True)
...     website = URLType()
... 
>>> person = Person({'name': u'Joe Strummer', 'website': 'http://soundcloud.com/joestrummer'})
/home/christian/.virtualenvs/inventory3/lib/python3.5/site-packages/schematics/transforms.py:105: SchematicsDeprecationWarning: Call to deprecated function _valid_input_keys.
  all_fields = schema._valid_input_keys
>>> 
```

Note: I did not check them all, just had this one fired when testing on python 2.6 (deprecated warnings are not shown on python 2.7/3.x by default unless you set PYTHONWARNINGS environment variable or use -Wd options, but they're still there nonetheless..)

**Comment by lkraider** [comment]
Yes, this is a reminder to myself. I've deprecated some accessors that moved between Model and Schema and some others that need rework, but didn't want to delay a release because of refactoring. I'll close this for now since moving away from those is in the plans already and shouldn't influence users of the library.

**Comment by centralniak** [comment]
I appreciate I'm replying to a closed ticket, but we are observing this in our project, too - and `schematics` is the only library in our stack triggering these warnings. Hence we would really like to avoid having to silence those `SchematicsDeprecationWarning`.

Do you need any help in getting this issue resolved?
