### ISSUE TITLE
Accessing ModelType instance

### ISSUE THREAD

**Issue by FrEaKmAn** [schematics/schematics#525]
Hello

Based on the #256, I'm able to access all fields using `self._fields` and read the value with `getattr(self, 'fieldname')`.

If I define ModelType directly as `field = ModelType(MyCustomClass)`, then I can easily access the value. But if I define it as @serializable

```
@serializable
def field(self):
    return ModelType(MyCustomClass)
```
then I cannot get value. How can I get the instance of the MyCustomClass? `getattr(field, 'field2name')` does not work.

**Comment by lkraider** [comment]
What you want to do is declare the type in the serializable decorator:
```python
class M(Model):
    @serializable(ModelType(MyCustomClass))
    def field(self):
        return MyCustomClass()

```
