### ISSUE TITLE
Can Model object be direct stored in memcache?

### ISSUE THREAD

**Issue by Garlandal** [schematics/schematics#526]
I have a application and with some reasons i need to add cache on the service layer，schematics has [serializable](https://schematics.readthedocs.io/en/latest/usage/exporting.html#serializable) feature and it works well.

i also wonder whether the Model Object can be direct stored in memcache, such as the `User` bellow, i test it before and find it also works well but not get some official explanation on doc.

```python
from schematics.types import IntType, DateTimeType, StringType
from schematics.types.compound import ModelType
from schematics.models import Model

class _Detail(Model):
    city = StringType()
    desc = StringType()


class User(Model):
    id = IntType()
    name = StringType()
    age = IntType()
    detail = ModelType(_Detail, default={})
    create_time = DateTimeType(default=datetime.datetime.now)
    update_time = DateTimeType(default=datetime.datetime.now)
```

Thank you very much.

**Comment by lkraider** [comment]
Hi, regarding storing Model instances directly, we don't have specific test cases to make sure it always work, but we are trying to make sure you can run them through pickle.

The best supported way would be to serialize and reinstantiate the Model from the data when retrieving it from the cache.

**Comment by Garlandal** [comment]
@lkraider pickle is a good point, appreciate your help, thanks~
