### ISSUE TITLE
Create a Timedelta/Duration type

### ISSUE THREAD

**Issue by gabisurita** [schematics/schematics#539]
Following what is implemented for ` DateTimeType` and `DateType`, I think it would be nice to have a `TimeDeltaType` for `datetime.timedelta` objects.

**Comment by lkraider** [comment]
Indeed, a PR is welcome!

**Comment by gabisurita** [comment]
Nice! I'll try to sketch something up later today.

**Comment by lkraider** [comment]
Released in 2.1 !
