### ISSUE TITLE
Support International Email Addresses in EmailType

### ISSUE THREAD

**Issue by niltz** [schematics/schematics#541]
It appears that the EmailType doesn't validate [international email addresses](https://en.wikipedia.org/wiki/Email_address#Internationalization_examples) that will be permitted with [RFC 6530](https://tools.ietf.org/html/rfc6530)
```
def test_international_emails(self):
        validator = EmailType()
        validator.validate(u'Pelé@example.com')
        validator.validate(u'δοκιμή@παράδειγμα.δοκιμή')
        validator.validate(u'我買@屋企.香港')
        validator.validate(u'甲斐@黒川.日本')
        validator.validate(u'чебурашка@ящик-с-апельсинами.рф')
        validator.validate(u'संपर्क@डाटामेल.भारत')
```

**Comment by lkraider** [comment]
Hi, thanks for the report. It seems the Type will have to be extended to add that. Let me know if you can provide a PR! :)

**Comment by AmicoJoules** [comment]
This came and bit me as well... maybe worth to revisit this
