### ISSUE TITLE
ETA for a new release

### ISSUE THREAD

**Issue by andreykurilin** [schematics/schematics#599]
Hi!
I see a bunch of deprecated warnings which are fixed with https://github.com/schematics/schematics/commit/e7a4ccc07543d0a6efecf12356ff812789dbfcfc , so I wonder when the new release is planned to be released?
Thanks in advance.

**Comment by andreykurilin** [comment]
@jmsdnns @bintoro @kracekumar 
Hi folks!
Sorry for direct ping, but there is no visible activity at schematics project for a while.
Is there any possibility of seeing any further work soon(i.e., merging new PRs, releasing new versions)?

**Comment by j2labs** [comment]
I am the original author of Schematics, but I have not maintained
Schematics for a long time. It seems as though there is a community here
that wants it to move forward yet no leader.

I got the idea to build a new form of Schematics a little while ago and
eventually posted a new thing called TypeRighter.

It is something I've used in several projects, though it hasn't existed for
very long. It is not a feature complete match for Schematics, but it isn't
far from that either. I attempted to build Schematics with a more mature
understanding of type theory. I started Schematics close to ten years ago,
after all, but it had a different name back then: *DictShield*.

I would welcome anyone who wants to join me in working on TypeRighter. I
believe the design is significantly cleaner, there is more work to do, and
some of the code was lifted from Schematics anyway.

https://github.com/jmsdnns/typerighter

**Comment by lingfish** [comment]
So, this project is stale?  Perhaps a toplevel note of that in the README...

**Comment by j2labs** [comment]
Seems fair, unless someone wants to step up

If that's been offered, please point me to it and I'll hook it up, assuming
there's a way to vaidate them as authors

**Comment by lkraider** [comment]
Hi @andreykurilin 

I'll try to review some more PRs and prepare a release. No real ETA yet, but soonish.

**Comment by jamiecook** [comment]
@j2labs - happy to help with maintenance - we're getting good value out of schematics. 
Will also have a look at typerighter

**Comment by lkraider** [comment]
Hi all, I've released v2.1.1 to PyPI with the master and a few of the pending PRs.

Please open a new issue in case you find any problems!
