### ISSUE TITLE
RecursionError when using @serializable

### ISSUE THREAD

**Issue by leofj** [schematics/schematics#610]
Hello,
when I try to serialize a field that already exists I get the error `RecursionError: maximum recursion depth exceeded`
Am I doing it wrong? I have a field called 'headquarters'. The class has fields like country, state and city. When I serialize I want to return a string "country, city".
Is that possible?

**Comment by lkraider** [comment]
Do you have some sample code?

**Comment by leofj** [comment]
Not anymore, I gave up using it last year
