### ISSUE TITLE
Project is still being maintened

### ISSUE THREAD

**Issue by rennerocha** [schematics/schematics#616]
Is this project still being maintained? Is there plans for new future releases?

**Comment by ahopkins** [comment]
Last commit to master December 2018. Last release to PyPI June 2018.

Looks dead to me.

**Comment by rennerocha** [comment]
Looks dead to me as well ... 
Just opened the issue to see if some maintainer suddenly reappears.

**Comment by lkraider** [comment]
There's a few PRs I was meaning to merge into a new release.

**Comment by rennerocha** [comment]
@lkraider it would be great if we have a new release with some PRs merged.
I am the maintainer of a project that uses schematics as an optional feature and I was considering remove it from there as the project looks dead. If a new release is made and the project is alive again, I will reconsider. 
Is there anything I can help to make a new release to happen soon?

**Comment by lkraider** [comment]
@rennerocha if you would like to point the PRs you are interested in, and if possible, test them, that would help for sure.

**Comment by ahopkins** [comment]
What is the maintainance plan of this project going forward?

**Comment by kstrauser** [comment]
I'm considering what it would look like to have a Schematics 3 release in the near-ish future. @lkraider, what do you think about #619 and friends?

**Comment by jamiecook** [comment]
@kstrauser and @lkraider, to be honest we'd be pretty keen on seeing things that are already in master released. There is a deprecation in validate.py which is fixed in master to allow type annotations in validator method calls. That would be sweet as we are trying to encourage users to annotate all their methods.

**Comment by lkraider** [comment]
Hi all, I've released v2.1.1 to PyPI with the master and a few of the pending PRs.

Please open a new issue in case you find any problems!

@kstrauser let's create a new issue for Schematics 3 discussion as well.
